/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'index',
	{
		type: 'category',
		label: 'Integration',
		collapsed: false,
		link: {
			type: 'doc',
			id: 'business-integration/index'},
			items:[
			'business-integration/getting_started',
			'business-integration/js_api',			
			'business-integration/web_integration',
			{
				type: 'category',
				label: 'Unity',
				link: {type: 'doc', id: 'business-integration/unity/index'},
				items:[
					'business-integration/unity/metaperson_loader',
					'business-integration/unity/windows_and_macos',
					'business-integration/unity/android_and_ios',
					'business-integration/unity/webgl',
					'business-integration/unity/vr',
					'business-integration/unity/metaperson_creator_unity_project',
					{
						type: 'category',
						label: 'Additional samples',
						link: {type: 'doc', id: 'business-integration/unity/additional_samples/index'},
						items: [
							'business-integration/unity/additional_samples/movement_sdk_integration',
							'business-integration/unity/additional_samples/photon_sample'
						]
					}
				]
			},
			{
				type: 'category',
				label: 'Unreal Engine',
				link: {type: 'doc', id: 'business-integration/ue/index'},
				items:[
					'business-integration/ue/overview',
					'business-integration/ue/github_sample',
					'business-integration/ue/marketplace_plugin',
					'business-integration/ue/animation_retargeting',
					'business-integration/ue/metaperson_creator_integration',					
				]
			},
			'business-integration/android',
			'business-integration/ios'
			
			
		]			
		
		
	},
	'rest_api',
	'mixamo',
	'faq'
  ],
  
};

export default sidebars;
