/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
	'leap',
  {
		type: 'category',
		label: 'MetaPerson Creator',
		link: {type: 'doc', id: 'index'},
		items:[
			'metaperson-creator/cartoonish'
		]
	},
	{
		type: 'category',
		label: 'Integration',
		collapsed: false,
		link: {
			type: 'doc',
			id: 'business-integration/index'},
			items:[
			'business-integration/getting_started',
			'business-integration/js_api',			
			{
				type: 'category',
				label: 'Web',
				link: {type: 'doc', id: 'business-integration/web_integration/index'},
				items:[
					'business-integration/web_integration/babylonjs',
					'business-integration/web_integration/threejs',
				]
			},
			{
				type: 'category',
				label: 'Unity',
				link: {type: 'doc', id: 'business-integration/unity/index'},
				items:[
					'business-integration/unity/metaperson_loader',
					'business-integration/unity/windows_and_macos',
					'business-integration/unity/android_and_ios',
					'business-integration/unity/webgl',
					'business-integration/unity/vr',
					'business-integration/unity/metaperson_creator_unity_project',
					{
						type: 'category',
						label: 'Additional samples',
						link: {type: 'doc', id: 'business-integration/unity/additional_samples/index'},
						items: [
							'business-integration/unity/additional_samples/movement_sdk_integration',
							'business-integration/unity/additional_samples/photon_sample',
							'business-integration/unity/additional_samples/rendering_sample',
							'business-integration/unity/additional_samples/eyes_animation_sample',
						]
					}
				]
			},
			{
				type: 'category',
				label: 'Unreal Engine',
				link: {type: 'doc', id: 'business-integration/ue/index'},
				items:[
					'business-integration/ue/overview',
					'business-integration/ue/github_sample',
					'business-integration/ue/import_editor',
					'business-integration/ue/marketplace_plugin',
					'business-integration/ue/animation_retargeting',
					'business-integration/ue/metaperson_creator_integration',					
				]
			},
			'business-integration/android',
			'business-integration/ios',
			{
				type: 'category',
				label: 'Release Notes',
				link: {type: 'doc', id: 'business-integration/release_notes/index'},
				items:[
					'business-integration/release_notes/desktop',
					'business-integration/release_notes/mobile',
				]
			}
		]			
	},	
	'rest_api',	
	{
		type: 'category',
		label: '3D Motion',
		link: {type: 'doc', id: '3dmotion/index'},
		items:[
			'3dmotion/mixamo',			
			'3dmotion/deepmotion',
		]
	},
	{
		type: 'category',
		label: 'Lipsync',
		link: {type: 'doc', id: 'lipsync/index'},
		items:[
			'lipsync/salsa',
			'lipsync/oculus_ue',
			'lipsync/oculus_unity'
		]
	},
	'faq'
  ],
  
};

export default sidebars;
